config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :integer          not null, primary key
#  name          :string
#  resource_type :string
#  resource_id   :integer
#  created_at    :datetime
#  updated_at    :datetime
#
# Indexes
#
#  index_roles_on_name                                    (name)
#  index_roles_on_name_and_resource_type_and_resource_id  (name,resource_type,resource_id)
#

class Role < ApplicationRecord
  has_and_belongs_to_many :users, join_table: :users_roles

  belongs_to :resource,
             polymorphic: true,
             optional: true

  validates :resource_type,
            inclusion: { in: Rolify.resource_types },
            allow_nil: true

  scopify
end

app/models/task.rb
# == Schema Information
#
# Table name: tasks
#
#  id         :integer          not null, primary key
#  name       :string
#  start_day  :datetime
#  end_day    :datetime
#  status     :integer          default("defualt")
#  state      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Task < ApplicationRecord
  enum status: { default: 0, accept: 1, in_process: 2, solve: 3 }

  scope :quite_old, -> { where(status: 0).where('start_day < ?', 5.days.ago) }

  def self.update_old_tasks
    if quite_old.count > 0
      slack_message
      quite_old.update_all(status: 3)
    end
  end

  def self.slack_message
    slack_notifier = 'Last week task ' + " ``` #{quite_old.map(&:name).join(',')} ``` " + ' was updated'

    Slack::Notifier.new('https://hooks.slack.com/services/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', username: 'Notifier').ping(slack_notifier)
  end
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  reset_password_token   :string
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  sign_in_count          :integer          default(0), not null
#  current_sign_in_at     :datetime
#  last_sign_in_at        :datetime
#  current_sign_in_ip     :inet
#  last_sign_in_ip        :inet
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
require 'application_responder'

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :find_tasks, only: [:index, :new, :create]
  respond_to :html, :js, :json

  def new
    @task = Task.new
  end

  def create
    @task = Task.create(task_params)
    StatusJob.set(wait: 5.days).perform_later(@task)
  end

  def update
  end

  private

  def find_tasks
    @tasks = Task.all
  end

  def task_params
    params.require(:task).permit(:name, :start_day, :end_day)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SlackNotification</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.slim
= simple_form_for @task, remote: true do |f|
  = f.input :name
  .row
    .col-md-6
      = f.input :start_day, as: :date_picker
    .col-md-6
      = f.input :end_day, as: :date_picker

  .text-xs-left
    = f.button :button, 'Cancel', type: :reset, class: 'btn btn-none btn-margin-left', id: 'button-cancel'
  .text-xs-right
    = f.button :submit, class: 'btn btn-success'
br
br

javascript:
  $( "#button-cancel" ).click(function() {
    $("#task-form").slideUp(500);
  });

  $( function() {
    $('.datetimepicker').datetimepicker();
  });

app/views/tasks/_task.html.slim
ul
  - if task.solve?
    h3 Done task
    li = task.name + " #{task.start_day.to_formatted_s(:short)}"

app/views/tasks/create.js.erb
$("#tasks").html("<%= escape_javascript(render @tasks) %>");

$("#task-form").slideUp(400);

app/views/tasks/destroy.html.slim
h1 Tasks#destroy
p Find me in app/views/tasks/destroy.html.slim

app/views/tasks/index.html.slim
H1.text-xs-center Tasks list
hr

.container 
  .row
    .col-md-12
      = link_to "New Task", new_task_path, remote: true, class: 'btn btn-primary'
      br

  .row
    .col-md-12
      #task-form

  br
  #tasks 
    = render @tasks

app/views/tasks/new.js.erb
$("#task-form").html("<%= j (render 'form' )%>");
$("#task-from").slideDown(400);

app/views/tasks/update.html.slim
h1 Tasks#update
p Find me in app/views/tasks/update.html.slim